# Generated by Django 6.0.2 on 2026-02-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié')], default='draft', max_length=10),
        ),
    ]
