# Generated by Django 6.0.2 on 2026-03-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_alter_like_unique_together_remove_article_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='article',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
